apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-metrics-example
  labels:
    app: prometheus-metrics-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-metrics-example
  template:
    metadata:
      labels:
        app: prometheus-metrics-example
    spec:
      containers:
      - name: prometheus-metrics-example
        image: harbor.euso.kr/base/prometheus-python-demo:latest
        ports:
        - containerPort: 80
        - containerPort: 8090
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-metrics-example
  labels:
    app: prometheus-metrics-example
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30091
  - name: metrics
    port: 8090
    targetPort: 8090
    nodePort: 30092
  selector:
    app: prometheus-metrics-example
