apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-metrics-example
  labels:
    app: prometheus-metrics-example
    release: monitoring
spec:
  endpoints:
  - port: metrics
  selector:
    matchLabels:
      app: prometheus-metrics-example
